version: "2"

services:
  audiowidgets:
    image: babymotte/react-audio-widgets-demo
    restart: always
    ports:
      - 8082:80
    environment:
      - VIRTUAL_HOST=ensemble.bbmsoft.net
      - VIRTUAL_PORT=9021
      - LETSENCRYPT_HOST=ensemble.bbmsoft.net
      - LETSENCRYPT_EMAIL=mbachmann@bbmsoft.net
      - USER_UID=1001
      - USER_GID=1001
    networks:
      - proxy-tier
      - nextcloud
      - default
    logging:
      options:
        max-size: "10M"
        max-file: "5"

networks:
  proxy-tier:
    external:
      name: nextcloud_proxy-tier
  nextcloud:
    external:
      name: nextcloud_default
